version: '3.8'

services:
  php:
    image: php:8.2-cli
    container_name: php_app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    command: ["php", "-S", "0.0.0.0:8000", "-t", "public"]
    environment:
      - DATABASE_URL=mysql://user:password@mysql:3307/app_db

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
