version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_docfav
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      mysql:
        condition: service_healthy  # ⬅️ Esperar a que MySQL esté listo
    environment:
      DATABASE_URL: mysql://user:password@mysql:3306/app_db

  mysql:
    image: mysql:5.7
    container_name: mysql_docfav
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3307:3306"
    volumes:
      - mysql_docfav_data:/var/lib/mysql
    healthcheck:  # ⬅️ Verifica que MySQL esté operativo
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  mysql_docfav_data: